<input type="text" name="search" id="search-places">
<script>
    function activateSearchPlaces () {
        var input = document.getElementById('search-places');
        var autocomplete = new google.maps.places.Autocomplete(input);
    }
</script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCpms4sntdy8vkodNvBlmhx_LGNgM5WBVk&libraries=places&callback=activateSearchPlaces"></script>